unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload plugin is not installed!'
end

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-10"

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "..", "/iso-build"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-STEP1
    sed -i "s/main/main contrib non-free/g" /etc/apt/sources.list
    apt-get --allow-releaseinfo-change update
    apt-get install -y \
      linux-headers-$(uname -r) \
      dkms build-essential linux-kbuild-4.19 linux-compiler-gcc-8-x86 \
      firmware-linux firmware-linux-free firmware-linux-nonfree firmware-misc-nonfree firmware-amd-graphics firmware-iwlwifi
  STEP1
  config.vm.provision :reload

  config.vm.provision "shell", inline: <<-STEP2
    apt-get install -y rsync git live-build debootstrap xorriso squashfs-tools genisoimage
  STEP2
end
