name: ci

on:
  workflow_dispatch:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Current platform
        run: uname -a
