name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Build environment setup
        run: |
          sudo apt-get -q update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -t focal-backports --no-install-recommends -y -q \
               apt-transport-https \
               bc \
               build-essential \
               ca-certificates \
               curl \
               debhelper-compat \
               debootstrap \
               genisoimage \
               gettext \
               git \
               gnupg2 \
               jq \
               po4a \
               rsync \
               software-properties-common \
               squashfs-tools \
               xorriso
            git clone --depth=1 --single-branch --recurse-submodules --shallow-submodules --branch='debian/1%20210407' 'https://salsa.debian.org/live-team/live-build.git' /tmp/live-build
            cd /tmp/live-build
            dpkg-buildpackage -b -uc -us
            sudo dpkg -i /tmp/live-build*.deb
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Show files
        run: |
          export IMAGE_DISTRIBUTION=bullseye
          sed -i "s/^[[:space:]]*#*[[:space:]]*\(export[[:space:]]*CHECKSUM_RELEASE=\).*/\1false/" $IMAGE_DISTRIBUTION/vars.txt
          cat $IMAGE_DISTRIBUTION/vars.txt
          sudo /usr/bin/env bash ./build.sh "$IMAGE_DISTRIBUTION"
